
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { useRouter } from 'next/navigation'
import { SessionProvider, SessionProviderProps } from 'next-auth/react'
import AuthProvider from '@/components/AuthProvider'
import Nav from '@/components/Nav'

const poppins = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: 'Next 14 App with Next Auth Using Typescript',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${poppins.className} bg-gray-100`}>
          <Nav />
          <div className="m-2">{children}</div>
        </body>
      </AuthProvider>
    </html>
  )
}
